name: PokéDrop Discord

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer une alerte Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content":"🟢 PokéDrop FR est en ligne !"}' \
            "$WEBHOOK_URL"
