name: PokéDrop Discord

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Envoyer une alerte Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$WEBHOOK" \
            -H "Content-Type: application/json" \
            -d '{
              "username":"PokéDrop FR",
              "embeds":[
                {
                  "title":"🎉 PokéDrop détecté",
                  "description":"Un produit Pokémon est disponible !",
                  "color":3066993,
                  "fields":[
                    {
                      "name":"🛒 Magasins surveillés",
                      "value":"Leclerc, Carrefour, Amazon, Micromania, Cultura"
                    }
                  ],
                  "footer":{
                    "text":"PokéDrop FR • Surveillance 24/7"
                  }
                }
              ]
            }'